---

- name: Manage baw-server development machine
  hosts: all
  vars:
    rvm_rubies:
      # use full 'ruby-*' name
      # last ruby listed is the default
      - "ruby-2.3.5"
    rvm_default_ruby_version: '{{ rvm_rubies | last if rvm_rubies and rvm_rubies is iterable else rvm_rubies }}'
    rvm_install_path: /usr/share/rvm
    rvm_path: /usr/share/rvm/bin/rvm
    postgresql_version: 9.3
  pre_tasks:
    - debug: var=ansible_ssh_user
  roles:
    - role: "/home/vagrant/.ansible/roles/ANXS.postgresql"
      # be careful when enabling this: anyone on public network could access db with
      # no password and admin access!
      #postgresql_listen_addresses: "*"
      postgresql_databases:
        - name: baw_local_dev
          owner: postgres          # optional; specify the owner of the database
      become: true
  tasks:
    - name: IMPORT | audio tools tasks
      import_tasks: audio_tools.yml
      tags: [ "audio_tools" ]
    - name: IMPORT | ruby tasks
      import_tasks: ruby.yml
      tags: [ "ruby" ]
    - name: APT | Install tools needed for installing pg gem
      apt:
        pkg: libpq-dev
        state: present
      become: true
    - name: APT | Install tools needed for working with postgres
      apt:
        pkg: postgresql-client
        state: present
      become: true
    - name: POSTGRES | Ensure postgres password is blank
      postgresql_user:
        db: baw_local_dev
        user: postgres
        password: NULL
    - name: APT | Install zip and unzip
      apt:
        pkg: zip
        state: present
      become: true