
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  TargetRubyVersion: 2.5
# Rails:
#   Enabled: true

# Customized options
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods:
    - resource
    - describe
    - shared_examples_for
Metrics/LineLength:
  Max: 120
Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/BracesAroundHashParameters:
  EnforcedStyle: braces
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
