
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
# Rails:
#   Enabled: true

# Customized options
Metrics/LineLength:
  Max: 120
Style/BracesAroundHashParameters:
  EnforcedStyle: braces
Style/WordArray:
  EnforcedStyle: brackets
