language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
before_script:
  - yes | cp lib/baw-workers/settings.travis.yml lib/baw-workers/settings.example.yml
before_install:
  - echo "Installing audio tools..."
  - sudo apt-get update -qq
  - sudo apt-get install -qq wavpack libsox-fmt-all sox shntool mp3splt libavcodec-extra-53 --fix-missing
  - mkdir tmp
  - wget http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.2014-03-02.tar.gz
  - tar xvzf ffmpeg.static.64bit.2014-03-02.tar.gz
  - rm ffmpeg.static.64bit.2014-03-02.tar.gz
  - sudo mv ffmpeg /usr/local/bin
  - sudo mv ffprobe /usr/local/bin
  - echo "...testing for audio tools..."
  - ffmpeg -version
  - mp3splt -version
  - sox --version
  - echo "...audio tools installed."
script:
  - bundle exec rspec