language: ruby
sudo: true
rvm:
- 2.3.5
#- 2.4.0 # Not ready for 2.4, need multiple bundle updates because of changes in native APIs
branches:
  only:
  - master
  - develop
gemfile: Gemfile
bundler_args: --without development production staging --jobs=3 --retry=3
addons:
  apt:
    packages:
    - python-pip
  postgresql: "9.3"
before_install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Install ansible roles (not actually needed but easier than special-casing playbook)
  - ansible-galaxy install -r provision/requirements.yml
  # execute the same playbook we use to set up our vagrant VMs
  - ansible-playbook -i "localhost," provision/vagrant.yml --skip-tags="ruby,postgres" --connection=local

  # check versions
  - which ffmpeg
  - ffmpeg -version
  - mp3splt -version
  - sox --version
before_script:
- yes | cp config/settings/test.travis.yml config/settings/test.yml
- psql -c 'create database myapp_test;' -U postgres
script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake
env:
  global:
    # Code climate token encrypted with travis gem (travis encrypt CODECLIMATE_REPO_TOKEN=...)
    - secure: JUFFho398MH3PBrEkE4lsuiBJG3J2WN3rscaxy49AnU60IM+45qkvxR6+eTkTtrc5mHhxBepPpNJNLuhiW5T32ckftxT7Ct0n/6FGykRIFixqXAWv91XfxkPrbfg2O/ll43RYqnbFW4LC/zNnp3us6LMKoL+7oxfFLowA9/1uoE=
    - RAILS_ENV=test
    - ANSIBLE_HOST_KEY_CHECKING=False
