language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
gemfile:
  - Gemfile
bundler_args: --without development production staging
before_script:
  - yes | cp config/settings/test.travis.yml config/settings/test.yml
  - psql -c 'create database myapp_test;' -U postgres
before_install:
  - echo "Installing audio tools..."
  - sudo apt-get update -qq
  - sudo apt-get install -qq wavpack sox shntool mp3splt libavcodec-extra-53 --fix-missing
  - pwd
  - mkdir tmp
  - wget http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.2014-03-02.tar.gz
  - tar xvzf ffmpeg.static.64bit.2014-03-02.tar.gz
  - mv ./ffmpeg ~/bin/
  - mv ./ffprobe ~/bin/
  - ls -la ~/bin
  - echo "...testing for audio tools..."
  - ffmpeg -version
  - mp3splt -version
  - sox --version
  - echo "...audio tools installed."
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake --trace
