language: ruby
rvm:
  - 1.9.3
  - 2.1.2
branches:
  only:
    - master
before_script:
  - yes | cp lib/settings/settings.travis.yml lib/settings/settings.default.yml
before_install:
  - echo "Installing audio tools..."
  - sudo apt-get update -qq
  - sudo apt-get -y install imagemagick wavpack libsox-fmt-all sox shntool mp3splt libav-tools --fix-missing
  - mkdir tmp
  - wget https://github.com/QutBioacoustics/baw-audio-tools/releases/download/v0.1.0/ffmpeg-git-20140817-64bit-static.tar.gz
  - tar xvzf ffmpeg-git-20140817-64bit-static.tar.gz
  - rm ffmpeg-git-20140817-64bit-static.tar.gz
  - sudo mv ffmpeg /usr/local/bin
  - sudo mv ffprobe /usr/local/bin
  - echo "...testing for audio tools..."
  - ffmpeg -version
  - mp3splt -version
  - sox --version
  - echo "...audio tools installed."
script:
  - bundle exec rspec
env:
  global:
    secure: "Kq1sbJ7fwl27/QICiZtzdPe9mmPbnQfgyOujm+stPTmnpHtYU1gfwJtyrw+bBi9INdxiZHTzPjRdLM36zWEysSi8HRySVkVCzG3fgG/AWvmTlqzBigLjlHV0Xhb9YRSb1FgbC2UNcp2YF4FcAdlFkrgRKWNxNGLAy4gyH3E9a3A="

