language: ruby
sudo: false
rvm:
- 2.2.3
- 2.2.5
- 2.3.1
branches:
  only:
  - master
  - develop
gemfile: Gemfile
bundler_args: --without development production staging --jobs=3 --retry=3
addons:
  apt:
    packages:
    - imagemagick
    - wavpack
    - libsox-fmt-all
    - sox
    - shntool
    - mp3splt
    - libav-tools
  postgresql: "9.3"
before_install:

  # download, extract, and add ffmpeg and ffprobe to path
  - mkdir /tmp/ffmpeg
  - wget http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz -O /tmp/ffmpeg/download-ffmpeg.tar.gz
  - tar -xzf /tmp/ffmpeg/download-ffmpeg.tar.gz -C /tmp/ffmpeg/
  - export PATH=/tmp/ffmpeg:$PATH

  # check versions
  - which ffmpeg
  - ffmpeg -version
  - mp3splt -version
  - sox --version
before_script:
- yes | cp config/settings/test.travis.yml config/settings/test.yml
- psql -c 'create database myapp_test;' -U postgres
script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake
env:
  global:
    # Code climate token encrypted with travis gem (travis encrypt CODECLIMATE_REPO_TOKEN=...)
    - secure: JUFFho398MH3PBrEkE4lsuiBJG3J2WN3rscaxy49AnU60IM+45qkvxR6+eTkTtrc5mHhxBepPpNJNLuhiW5T32ckftxT7Ct0n/6FGykRIFixqXAWv91XfxkPrbfg2O/ll43RYqnbFW4LC/zNnp3us6LMKoL+7oxfFLowA9/1uoE=
    - RAILS_ENV=test
