version: '3.4'
volumes:
  postgres-data:
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - baw_docker_network
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - baw_docker_network
  web:
    #image: qutecoacoustics/baw-server:dev
    build:
      context: .
      target: baw-server-dev
    entrypoint: ./provision/entrypoint.sh bundle exec passenger start
    #command: bundle exec passenger start
    #command: /bin/bash
    environment:
      RAILS_ENV: development

    # command:
    volumes:
      - type: bind
        source: ./
        target: /home/baw_web/baw-server
      - type: bind
        source: ./provision/Passengerfile.development.json
        target: /home/baw_web/baw-server/Passengerfile.json
    ports:
      - "3000:3000"
    networks:
      - baw_docker_network
    depends_on:
      - db
      - redis

networks:
  baw_docker_network:
