version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - baw_docker_network
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - baw_docker_network
  workers:
    build:
      context: .
      target: baw-server-dev
    command: >-
      bundle exec rake baw:worker:run['/home/baw_web/baw-server/config/settings/default.yml']
    entrypoint: []
    networks:
      - baw_docker_network
    ports:
      # rdebug-ide port (mapped for workers)
      - "1235:1234"
      - "26162:26162"
    volumes:
      - type: bind
        source: ./
        target: /home/baw_web/baw-server
      # see comment on volume declaration below
      - type: volume
        source: baw_docker_shared_storage
        target: /home/baw_web/baw-server/tmp

    working_dir: /home/baw_web/baw-server
    depends_on:
      - db
      - redis
  web:
    #image: qutecoacoustics/baw-server:dev
    build:
      context: .
      target: baw-server-dev
    entrypoint: ""
    command: /home/baw_web/baw-server/provision/entrypoint.sh bundle exec passenger start
    environment:
      RAILS_ENV: development
    user: baw_web
    volumes:
      - type: bind
        source: ./
        target: /home/baw_web/baw-server
      # see comment on volume declaration below
      - type: volume
        source: baw_docker_shared_storage
        target: /home/baw_web/baw-server/tmp
    ports:
      - "3000:3000"
      # rdebug-ide port
      - "1234:1234"
    networks:
      - baw_docker_network
    depends_on:
      - db
      - redis
      - workers
networks:
  baw_docker_network:
volumes:
  # We're using a volume mount for tmp because it offers better performance
  # than a bind mount. It also does not seem to suffer from cache/metadata
  # problems that bind mounts (see caching in cifs/nfs).
  # The downside to this is that we can no longer access files in /tmp on
  # out hosts for dev work.
  baw_docker_shared_storage:
  postgres-data:
