version: '3.4'
volumes:
  postgres-data:
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - baw_docker_network
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - baw_docker_network
  workers:
    build:
      context: .
      target: baw-server-dev
    command: >-
      ../bin/bundle exec rake baw:worker:run['/home/baw_web/baw-server/baw-workers/lib/settings/settings.default.yml']
    entrypoint: []
    networks:
      - baw_docker_network
    volumes:
      - type: bind
        source: ./
        target: /home/baw_web/baw-server
    working_dir: /home/baw_web/baw-server/baw-workers
  web:
    #image: qutecoacoustics/baw-server:dev
    build:
      context: .
      target: baw-server-dev
    entrypoint: ""
    command: /home/baw_web/baw-server/provision/entrypoint.sh bundle exec passenger start
    environment:
      RAILS_ENV: development
    user: baw_web
    volumes:
      - type: bind
        source: ./
        target: /home/baw_web/baw-server
    ports:
      - "3000:3000"
      # rdebug-ide port
      - "1234:1234"
    networks:
      - baw_docker_network
    depends_on:
      - db
      - redis

networks:
  baw_docker_network:
