---
openapi: 3.0.1
info:
  title: BAW API
  version: v2
produces:
- application/json
consumes:
- application/json
paths:
  "/projects/filter":
    post:
      summary: filter project
      security:
      - basic_auth_with_token: []
      responses:
        '200':
          description: successful
          content: {}
  "/projects":
    get:
      summary: list projects
      security:
      - basic_auth_with_token: []
      responses:
        '200':
          description: successful
          content: {}
    post:
      summary: create project
      security:
      - basic_auth_with_token: []
      responses:
        '200':
          description: successful
          content: {}
  "/projects/new":
    get:
      summary: new project
      security:
      - basic_auth_with_token: []
      responses:
        '200':
          description: successful
          content: {}
  "/projects/{id}/edit":
    get:
      summary: edit project
      security:
      - basic_auth_with_token: []
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content: {}
  "/projects/{id}":
    get:
      summary: show project
      security:
      - basic_auth_with_token: []
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content: {}
    patch:
      summary: update project
      security:
      - basic_auth_with_token: []
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content: {}
    put:
      summary: update project
      security:
      - basic_auth_with_token: []
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content: {}
    delete:
      summary: delete project
      security:
      - basic_auth_with_token: []
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost
components:
  securitySchemes:
    basic_auth_with_token:
      type: http
      scheme: basic
    auth_token_query_string:
      type: apiKey
      name: auth_token
      in: query_string
  schemas:
    standard_response:
      type: object
      properties:
        meta:
          type: object
        data:
          type: array
    error_object:
      type: object
      properties: {}
