# Using SettingsLogic, see https://github.com/binarylogic/settingslogic
# settings loaded in model/settings.rb
# Accessible through Settings.key
# Environment specific settings expected in config/settings/{environment_name}.yml
defaults: &defaults
  host:
    name: localhost
    port: 3030
  smtp:
    # see http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
    ######################################################
    # these values are read for config.action_mailer.smtp_settings in
    # File environments/{environment_name}.rb
    ######################################################
    address: smtp.address
    port: smtp.port
    domain: domain.com
    user_name: username
    authentication: login
    password: password
  db:
    ######################################################
    # these values are read by config/database.yml
    ######################################################
    adapter: sqlite3
    encoding: utf8
    reconnect: false
    database: db/default.sqlite3
    pool: 5
    username: root
    password:
    host: localhost
  exception_notification:
    email_prefix: '[prefix]'
    sender_address: address@example.com
    exception_recipients: address@example.com
  devise:
    ######################################################
    # these values are read for config.{key} in
    # File devise.rb #
    ######################################################
    mailer_sender: address@example.com
    pepper: 128 char random pepper 128 char random pepper
    expire_auth_token_on_timeout: true
    secret_key: 128 char random pepper 128 char random pepper
  ######################################################
  # File secret_token.rb #
  ######################################################
  secret_token: some long secret token - at least 30 chars, all random
  paths:
    image_magick_dir: <%= Rails.root %>/tmp/_image-magick
    ######################################################
    # these paths must align with the paths used by the harvester defined in
    # File lib/external/harvester/default.yml
    ######################################################
    original_audios:
      - <%= Rails.root %>/tmp/_original_audio
    cached_spectrograms:
      - <%= Rails.root %>/tmp/_cached_spectrogram
    cached_audios:
      - <%= Rails.root %>/tmp/_cached_audio
    analysis_scripts:
      - <%= Rails.root %>/tmp/_analysis_script
    analysis_results:
      - <%= Rails.root %>/tmp/_analysis_result
    analysis_runs:
      - <%= Rails.root %>/tmp/_analysis_run
    harvester_base: <%= Rails.root %>/tmp/_harvester_to_do
  harvester_config_file: harvest.yml
  harvester:
    email: address+harvester@example.com
    password: password
  admin_user:
    email: address+admin@example.com
    password: password
  cached_audio_defaults:
    mp3:
      channel: 0
      sample_rate: 22050
    webm:
      channel: 0
      sample_rate: 22050
    ogg:
      channel: 0
      sample_rate: 22050
  cached_spectrogram_defaults:
    png:
      channel: 0
      sample_rate: 22050
      window: 512
      colour: 'g'

development:
  <<: *defaults
  # add overwrites in config/settings/{environment_name}.yml
test:
  <<: *defaults
  # add overwrites in config/settings/{environment_name}.yml
staging:
  <<: *defaults
  # add overwrites in config/settings/{environment_name}.yml
production:
  <<: *defaults
  # add overwrites in config/settings/{environment_name}.yml
