# The main purpose of this job is to check that developers on 
# Windows or Mac can build the dockerfile and lauch docker-compose.
# As much as we'd like docker to be the universal abstraction, reality
# is more complex!
name: Docker Image Development test

on:
  push:
    branches: [ master ]

jobs:

  build-docker:
    name: "Test dockerfile build and docker-compose on ${{ matrix.os }}, with buildkit: ${{ matrix.buildkit }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        buildkit: [0] # not supported by default yet on GA
        # our normal CI runs on ubuntu-latest so we won't double up on the work here
        os: [windows-latest, macos-latest]


    steps:
    - uses: actions/checkout@v2
      
    # https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981
    - name: Install docker (Mac)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install docker-machine docker && docker-machine start
        sudo docker --version

    - name: Install docker-desktop (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install --yes docker-desktop
        docker --version

    # by default the user on GH seems to have the UID 1001
    # however our docker container expects a uid of 1000.
    # This is not an issue in Docker since we chown files when they are added.
    # However when docker-compose bind mounts the volumes for development
    # the permissions of the files reflect those that are on the host, in the
    # GH action case uid 1001 and gid 116.
    - name: Set permissions for checked out files
      if: ${{ matrix.os !=  'windows-latest' }}
      run: sudo chmod -R o=u .
      
    - name: Build the Docker image
      run: docker build .
      env:
        DOCKER_BUILDKIT:  ${{ matrix.buildkit }} 
      
    - name: Check compose file can be booted
      run: docker-compose -d
      env:
        DOCKER_BUILDKIT:  ${{ matrix.buildkit }} 

    - name: Stop docker-compose
      if: ${{ always() }}
      run: docker-compose stop
